# Generated by Django 2.0.5 on 2018-07-27 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0003_auto_20180727_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='best_combination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='combination_result', to='pokerstats.Round'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='best_winning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_result', to='pokerstats.Round'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_result', to='pokerstats.Game'),
        ),
    ]
