# Generated by Django 2.0.5 on 2018-07-27 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0004_auto_20180727_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Game'),
        ),
    ]
