# Generated by Django 2.0.5 on 2018-07-27 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0005_auto_20180727_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='pokerstats.Game'),
        ),
    ]
