# Generated by Django 2.0.5 on 2018-07-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0007_auto_20180727_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='pokerstats.Game'),
        ),
    ]
