# Generated by Django 2.0.5 on 2018-07-28 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0008_auto_20180728_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='best_combination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_combination_games', to='pokerstats.Round'),
        ),
        migrations.AlterField(
            model_name='game',
            name='best_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_result_games', to='pokerstats.GameResult'),
        ),
        migrations.AlterField(
            model_name='game',
            name='best_winning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_winning_games', to='pokerstats.Round'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='best_combination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_combination_results', to='pokerstats.Round'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='best_winning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_winning_results', to='pokerstats.Round'),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='pokerstats.Team'),
        ),
    ]
