version: '3'
services:

  nginx:
    build: nginx/
    image: pstats_nginx
    container_name: pstats_nginx
    restart: unless-stopped
    volumes:
      - static:/var/www/pstats
#      - ../server/static_root:/var/www/pstats
    ports:
      - "80:80"

  pstats:
    build: ../server
    image: pstats
    container_name: pstats
    restart: unless-stopped
    command: python manage.py runserver 0:80
    volumes:
#      - ../server/:/app
      - static:/app/static_root
    depends_on:
      - db
    expose:
      - "80"
    env_file:
      - .env

  db:
    image: postgres:10
    container_name: pstats_db
    restart: unless-stopped
    expose:
      - "5432"
    env_file:
      - .env

volumes:
  static: