# Generated by Django 2.0.5 on 2018-05-06 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyChips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_stake', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('place', models.IntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Game')),
            ],
        ),
        migrations.CreateModel(
            name='RoundResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('combination', models.CharField(blank=True, choices=[('1', 'High Card'), ('2', 'Pair'), ('3', 'Two Pairs'), ('4', 'Three of a Kind'), ('5', 'Straight'), ('6', 'Flush'), ('7', 'Full House'), ('8', 'Four of a Kind'), ('9', 'Straight Flush'), ('10', 'Royal Flush')], max_length=16, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Round')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(to='pokerstats.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='pokerstats.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Team'),
        ),
        migrations.AddField(
            model_name='buychips',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Game'),
        ),
        migrations.AddField(
            model_name='buychips',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Player'),
        ),
    ]
