# Generated by Django 2.0.5 on 2018-07-01 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_stake', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rebuy', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rebuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('combination', models.SmallIntegerField(blank=True, choices=[(1, 'High Card'), (2, 'Pair'), (3, 'Two Pairs'), (4, 'Three Of A Kind'), (5, 'Straight'), (6, 'Flush'), (7, 'Full House'), (8, 'Four Of A Kind'), (9, 'Straight Flush'), (10, 'Royal Flush')], null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Game')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Player')),
            ],
        ),
        migrations.AddField(
            model_name='rebuy',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Round'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_team', to='pokerstats.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(blank=True, to='pokerstats.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='best_combination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_player_combination', to='pokerstats.Round'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='best_winning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_player_winning', to='pokerstats.Round'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Game'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='best_combination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_game_combination', to='pokerstats.Round'),
        ),
        migrations.AddField(
            model_name='game',
            name='best_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_result', to='pokerstats.GameResult'),
        ),
        migrations.AddField(
            model_name='game',
            name='best_winning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_game_winning', to='pokerstats.Round'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='pokerstats.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Team'),
        ),
    ]
