# Generated by Django 2.0.5 on 2018-05-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0004_auto_20180506_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='init_stake',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
