# Generated by Django 2.0.5 on 2018-05-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0005_game_init_stake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='start_stake',
        ),
    ]
