# Generated by Django 2.0.5 on 2018-05-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0006_remove_game_start_stake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buychips',
            name='game',
        ),
        migrations.RemoveField(
            model_name='buychips',
            name='player',
        ),
        migrations.DeleteModel(
            name='BuyChips',
        ),
    ]
