# Generated by Django 2.0.5 on 2018-05-13 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0007_auto_20180513_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rebuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Player')),
            ],
        ),
    ]
