# Generated by Django 2.0.5 on 2018-05-13 08:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0008_rebuy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundresult',
            name='round',
        ),
        migrations.AddField(
            model_name='roundresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundresult',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roundresult',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
