# Generated by Django 2.0.5 on 2018-05-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0009_auto_20180513_0800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='game',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
