# Generated by Django 2.0.5 on 2018-05-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0011_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundresult',
            name='created',
        ),
        migrations.RemoveField(
            model_name='roundresult',
            name='game',
        ),
        migrations.AddField(
            model_name='roundresult',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pokerstats.Round'),
            preserve_default=False,
        ),
    ]
