# Generated by Django 2.0.5 on 2018-05-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0013_auto_20180513_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rebuy',
            name='game',
        ),
    ]
