# Generated by Django 2.0.5 on 2018-05-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0015_auto_20180513_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rebuy',
            name='round',
        ),
        migrations.AddField(
            model_name='roundresult',
            name='rebuy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='Rebuy',
        ),
    ]
