# Generated by Django 2.0.5 on 2018-05-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0016_auto_20180513_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundresult',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='roundresult',
            name='is_winner',
        ),
        migrations.AddField(
            model_name='roundresult',
            name='win',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
