# Generated by Django 2.0.5 on 2018-05-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0017_auto_20180513_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameresult',
            old_name='amount',
            new_name='rebuy',
        ),
        migrations.RemoveField(
            model_name='gameresult',
            name='place',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='win',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
