# Generated by Django 2.0.5 on 2018-05-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerstats', '0019_auto_20180526_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameresult',
            old_name='total',
            new_name='profit',
        ),
        migrations.RemoveField(
            model_name='roundresult',
            name='total',
        ),
    ]
